version: "3.7"

services: 
    flask:
        build: ./flask
        container_name: flask
        restart: always
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "8080:8080"

networks:
  default:
    external:
      name: flask-nginx
